### ISSUE TITLE
Nelkir wont progress "The Whispering Door" Quest 

### ISSUE THREAD

**Issue by ghost** [Lost-Outpost/septimus#447]
After being level 27-28 you can get dialogue at whiterun inn , about troubled children from the jarl, the player goes and speaks to the jarl, and the quest starts, the first ting the player must do is talk to nelkir, nelkir will talk, but no quest dialouge will be brought up about the jarl needing you to speak to nalkir,

**Comment by SpookyClaudia** [comment]
something I forgot to add - disable and enable does not work for this instance , where duplicating the child brings up dialogue box , to the new npc nalkir, and the only way to progress is console commands.

**Comment by Guitarninja2** [comment]
Duplicating the npc does give you the dialogue though?

**Comment by SpookyClaudia** [comment]
Duplicating gives the “the jarl asked me to speak to you” but after you listen to the door, and ask you to speak to the “dark child again” there is no more dialogue to progress about getting the key, you must engage console commands and this point, as no further dialogue happens when you duplicate/disable/enable the npc for this quest

**Comment by Guitarninja2** [comment]
That is bizarre yeah. I think I looked into the quest before also and there was nothing modifying it. I'll have to look again in xEdit.

**Comment by SpookyClaudia** [comment]
Let me know if you ever find the issue, I don’t mind using console commands to complete the quest for now :) thanks for the support! If you end up finding a fix I might need to implement it to titans list elysium to see if it works there too ,
