### ISSUE TITLE
Septimus 3 AE "Conjure Will-O-Wisp" CTD

### ISSUE THREAD

**Issue by Nebula-Stargazer** [Lost-Outpost/septimus#475]
Simply what the title says. 
Summoning a Will-O-Wisp with the spell causes an almost instant CTD, seemingly when the game tries to load the creature.

**Comment by Xgatt** [comment]
Confirmed it's happening to me too. Already checked missing mesh, so it's not that. I'll see if there are scripts or packages running. No crashlogs generated from this either.

**Comment by Samutz** [comment]
I took the time to look in to this and found the issue.
Bruma's ARMA record for the wisp (CYRNakedWillotheWisp) has a mesh set that it can't handle I guess. Changing it to the witchlight's mesh (since the wisp is based on it) fixes it.

Here's an ESL-flagged ESP for those that want a quick fix.
[bruma-willothewisp-crashfix.zip](https://github.com/Lost-Outpost/septimus/files/9155716/bruma-willothewisp-crashfix.zip)

![image](https://user-images.githubusercontent.com/767817/180117489-618ccb76-0a92-4a79-b1cb-39668819a756.png)

Side note: Weirdly the crash happens in vanilla SE too (only DLC, CC, and Bruma loaded). This fix works there as well, except that the wisp doesn't look right, like it's missing textures or something. Maybe something in the patches included in Septimus corrects it. I didn't take the time to load all of the Bruma patches in to the vanilla SE setup to see.
